### ISSUE TITLE
Simplify pre-commit hook installation

### ISSUE THREAD

**Issue by sstallion** [sstallion/vimwiki-cli#7]
A command should be added to simplify installing [scripts/pre-commit.sh](https://github.com/sstallion/vimwiki-cli/blob/master/scripts/pre-commit.sh) to wikis managed by git.

**Comment by sstallion** [comment]
Fixed by @jfishe in #14.

**Comment by jfishe** [comment]
If you want to see the messages from the pre-commit hook, e.g:

```text
vim|wiki: Generating links...done.
vim|wiki: Generating diary links...done.
vim|wiki: Rebuilding tag metadata...done.
vim|wiki: Generating tag links...done.
vim|wiki: Converting all wiki pages to HTML...done.
```

Add `verbose: true` in `.pre-commit-config.yaml`:

```yaml
repos:
    - repo: https://github.com/sstallion/vimwiki-cli
    rev: v1.2.0
    hooks:
      - id: vimwiki-cli
        verbose: true
```
